export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SHOW_LISTINGS = 'SHOW_LISTINGS';
export const DELETE_LISTING = 'DELETE_LISTING';